name: Publish AKS weekly digest (PowerShell)

on:
  schedule:
    - cron: '7 9 * * 0'      # Sundays at 09:07 UTC
  workflow_dispatch:

jobs:
  publish-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PowerShell 7 is preinstalled
        run: pwsh -v

      - name: Generate HTML JSON (content + hash)
        id: gen
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OpenAIKey: ${{ secrets.OPENAI_API_KEY }}
          AZURE_OPENAI_APIURI:       ${{ secrets.AZURE_OPENAI_APIURI }}
          AZURE_OPENAI_KEY:          ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_API_VERSION:  ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_DEPLOYMENT:   ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
        run: |
          ./.github/scripts/generate-aks-updates.ps1 1> out.json
          Write-Host "Generated out.json ($((Get-Item out.json).Length) bytes)"
          $json = Get-Content out.json -Raw | ConvertFrom-Json
          Set-Content -LiteralPath digest.html -Value $json.digest_html -Encoding UTF8
          Set-Content -LiteralPath digest.title -Value $json.digest_title -Encoding UTF8

      - name: Create weekly WP post
        run: |
          if [ ! -s digest.html ]; then
            echo "No digest content — skipping weekly post."
            exit 0
          fi

          WP_API="${{ secrets.WP_URL }}/wp-json/wp/v2/posts"
          TITLE=$(cat digest.title)

          jq -n --rawfile content digest.html --arg title "$TITLE" \
            '{title: $title,
              status: "publish",
              categories: [261],
              content: "<!-- wp:html -->\n\($content)\n<!-- /wp:html -->",
              comment_status: "closed"}' \
            > "$RUNNER_TEMP/wp-weekly.json"

          curl -sSf -X POST "$WP_API" \
            -u "${{ secrets.WP_USER }}:${{ secrets.WP_APP_PASSWORD }}" \
            -H "Content-Type: application/json" \
            --data-binary @"$RUNNER_TEMP/wp-weekly.json"